# Generated by Django 3.0.4 on 2020-03-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('我', models.CharField(max_length=10)),
                ('爱', models.CharField(max_length=255)),
                ('黑', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('名字', models.CharField(max_length=255)),
                ('不知道', models.FloatField()),
                ('额', models.IntegerField()),
                ('网页', models.CharField(max_length=2036)),
            ],
        ),
    ]
